const departmentActionsTypes = {
  CHANGE_DEPARTMENT: "CHANGE_DEPARTMENT",
  FETCH_DEPARTMENT_START: "FETCH_DEPARTMENT_START",
  FETCH_DEPARTMENT_SUCCESS: "FETCH_DEPARTMENT_SUCCESS",
  FETCH_DEPARTMENT_FAILURE: "FETCH_DEPARTMENT_FAILURE"
};

export default departmentActionsTypes;
